### ISSUE TITLE
Object serialisation to MDict using To<T> and From<T>

### ISSUE THREAD

**Issue by NoahHahm** [caesay/MPack#8]
hi. @caesay 
are there any plans to support the Object type?
MPack is very lightweight and easy to use.

**Comment by caesay** [comment]
Are you referring to the `MDict` class which is an object/map? if this is not what you are asking about, please point to exactly what in the messagepack spec you'd like implemented: https://github.com/msgpack/msgpack/blob/master/spec.md

**Comment by NoahHahm** [comment]
It seems that Map is not supported for From/To.

**Comment by caesay** [comment]
I understand, you want the object to be serialised/deserialized to/from an MDict. I'll consider this!

**Comment by caesay** [comment]
I have written a very basic object serializer in v2.1.1. It does not emit type annotations, so it will only work properly if you are serializing from/to concrete types (rather than `object` or some base class)
